//
// streamTypeDefineTest.cs
//
// This file was generated by XMLSpy 2008r2sp2 Enterprise Edition.
//
// YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
// OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
//
// Refer to the XMLSpy Documentation for further details.
// http://www.altova.com/xmlspy
//


using System;
using Altova.Types;

namespace streamTypeDefine
{
	/// <summary>
	/// Summary description for streamTypeDefineTest.
	/// </summary>
	class streamTypeDefineTest
	{
		protected static void Example()
		{
			//
			// TODO:
			//   Insert your code here...
			//
			// Example code to create and save a structure:
			//   streamTypeDefine.streamTypeDefine2 doc = streamTypeDefine.streamTypeDefine2.CreateDocument();			
			//   streamTypeDefine.urlType root = doc.url.Append();
			//   ...
			//   doc.SaveToFile("streamTypeDefine1.xml", true);
			//
			// Example code to load and save a structure:
			//   streamTypeDefine.streamTypeDefine2 doc = streamTypeDefine.streamTypeDefine2.LoadFromFile("streamTypeDefine1.xml");
			//   streamTypeDefine.urlType root = doc.url.First;
			//   ...
			//   doc.SaveToFile("streamTypeDefine1.xml", true);

		}

		/// <summary>
		/// The main entry point for the application.
		/// </summary>
		[STAThread]
		public static int Main(string[] args)
		{
			try
			{
				Console.WriteLine("streamTypeDefine Test Application");
				Example();
				Console.WriteLine("OK");
				return 0;
			}
			catch (Exception e)
			{
				Console.WriteLine(e);
				return 1;
			}
		}
	}
}
