#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IP_stream
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="23A")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertciBVCI(ciBVCI instance);
    partial void UpdateciBVCI(ciBVCI instance);
    partial void DeleteciBVCI(ciBVCI instance);
    partial void InsertimeiType(imeiType instance);
    partial void UpdateimeiType(imeiType instance);
    partial void DeleteimeiType(imeiType instance);
    partial void InsertmsIMEI(msIMEI instance);
    partial void UpdatemsIMEI(msIMEI instance);
    partial void DeletemsIMEI(msIMEI instance);
    partial void InsertmLocatingType(mLocatingType instance);
    partial void UpdatemLocatingType(mLocatingType instance);
    partial void DeletemLocatingType(mLocatingType instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::IP_stream.Properties.Settings.Default._23AConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<IP_stream> IP_stream
		{
			get
			{
				return this.GetTable<IP_stream>();
			}
		}
		
		public System.Data.Linq.Table<ciBVCI> ciBVCI
		{
			get
			{
				return this.GetTable<ciBVCI>();
			}
		}
		
		public System.Data.Linq.Table<imeiType> imeiType
		{
			get
			{
				return this.GetTable<imeiType>();
			}
		}
		
		public System.Data.Linq.Table<msIMEI> msIMEI
		{
			get
			{
				return this.GetTable<msIMEI>();
			}
		}
		
		public System.Data.Linq.Table<mLocatingType> mLocatingType
		{
			get
			{
				return this.GetTable<mLocatingType>();
			}
		}
		
		public System.Data.Linq.Table<ciCoverType> ciCoverType
		{
			get
			{
				return this.GetTable<ciCoverType>();
			}
		}
		
		public System.Data.Linq.Table<Gb_Paging_PS> Gb_Paging_PS
		{
			get
			{
				return this.GetTable<Gb_Paging_PS>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.IP_stream")]
	public partial class IP_stream
	{
		
		private System.Nullable<int> _FileNum;
		
		private System.Nullable<int> _PacketNum;
		
		private System.Nullable<int> _BeginFrameNum;
		
		private System.Nullable<System.DateTime> _PacketTime;
		
		private System.Nullable<int> _PacketTime_ms_;
		
		private string _DumpFor;
		
		private System.Nullable<int> _IPstream;
		
		private System.Nullable<int> _IPstream_PackLen;
		
		private string _IPstream_MsgType;
		
		private string _bvci;
		
		private string _tlli;
		
		private string _link;
		
		private string _http_uri;
		
		private string _http_host;
		
		private string _http_x_online;
		
		private string _wsp_uri;
		
		private string _ip_s;
		
		private string _ip_d;
		
		private string _tcp_s;
		
		private string _tcp_d;
		
		private string _udp_s;
		
		private string _udp_d;
		
		private string _lac;
		
		private string _ci;
		
		private string _http_type;
		
		private string _wsp_type;
		
		private string _smtp_type;
		
		private string _rtsp_type;
		
		private System.Nullable<int> _ip_length;
		
		private string _imei;
		
		private string _mmse;
		
		private string _bitrorrent;
		
		private string _oicqVersion;
		
		private string _edonkey;
		
		private string _imsi;
		
		public IP_stream()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FileNum", DbType="Int")]
		public System.Nullable<int> FileNum
		{
			get
			{
				return this._FileNum;
			}
			set
			{
				if ((this._FileNum != value))
				{
					this._FileNum = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PacketNum", DbType="Int")]
		public System.Nullable<int> PacketNum
		{
			get
			{
				return this._PacketNum;
			}
			set
			{
				if ((this._PacketNum != value))
				{
					this._PacketNum = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BeginFrameNum", DbType="Int")]
		public System.Nullable<int> BeginFrameNum
		{
			get
			{
				return this._BeginFrameNum;
			}
			set
			{
				if ((this._BeginFrameNum != value))
				{
					this._BeginFrameNum = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PacketTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> PacketTime
		{
			get
			{
				return this._PacketTime;
			}
			set
			{
				if ((this._PacketTime != value))
				{
					this._PacketTime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[PacketTime(ms)]", Storage="_PacketTime_ms_", DbType="Int")]
		public System.Nullable<int> PacketTime_ms_
		{
			get
			{
				return this._PacketTime_ms_;
			}
			set
			{
				if ((this._PacketTime_ms_ != value))
				{
					this._PacketTime_ms_ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DumpFor", DbType="NVarChar(30)")]
		public string DumpFor
		{
			get
			{
				return this._DumpFor;
			}
			set
			{
				if ((this._DumpFor != value))
				{
					this._DumpFor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IPstream", DbType="Int")]
		public System.Nullable<int> IPstream
		{
			get
			{
				return this._IPstream;
			}
			set
			{
				if ((this._IPstream != value))
				{
					this._IPstream = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IPstream_PackLen", DbType="Int")]
		public System.Nullable<int> IPstream_PackLen
		{
			get
			{
				return this._IPstream_PackLen;
			}
			set
			{
				if ((this._IPstream_PackLen != value))
				{
					this._IPstream_PackLen = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IPstream_MsgType", DbType="NVarChar(200)")]
		public string IPstream_MsgType
		{
			get
			{
				return this._IPstream_MsgType;
			}
			set
			{
				if ((this._IPstream_MsgType != value))
				{
					this._IPstream_MsgType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bvci", DbType="NVarChar(50)")]
		public string bvci
		{
			get
			{
				return this._bvci;
			}
			set
			{
				if ((this._bvci != value))
				{
					this._bvci = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tlli", DbType="NVarChar(200)")]
		public string tlli
		{
			get
			{
				return this._tlli;
			}
			set
			{
				if ((this._tlli != value))
				{
					this._tlli = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_link", DbType="NVarChar(200)")]
		public string link
		{
			get
			{
				return this._link;
			}
			set
			{
				if ((this._link != value))
				{
					this._link = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_http_uri", DbType="NVarChar(200)")]
		public string http_uri
		{
			get
			{
				return this._http_uri;
			}
			set
			{
				if ((this._http_uri != value))
				{
					this._http_uri = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_http_host", DbType="NVarChar(200)")]
		public string http_host
		{
			get
			{
				return this._http_host;
			}
			set
			{
				if ((this._http_host != value))
				{
					this._http_host = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_http_x_online", DbType="NVarChar(200)")]
		public string http_x_online
		{
			get
			{
				return this._http_x_online;
			}
			set
			{
				if ((this._http_x_online != value))
				{
					this._http_x_online = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_wsp_uri", DbType="NVarChar(200)")]
		public string wsp_uri
		{
			get
			{
				return this._wsp_uri;
			}
			set
			{
				if ((this._wsp_uri != value))
				{
					this._wsp_uri = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ip_s", DbType="NVarChar(200)")]
		public string ip_s
		{
			get
			{
				return this._ip_s;
			}
			set
			{
				if ((this._ip_s != value))
				{
					this._ip_s = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ip_d", DbType="NVarChar(200)")]
		public string ip_d
		{
			get
			{
				return this._ip_d;
			}
			set
			{
				if ((this._ip_d != value))
				{
					this._ip_d = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tcp_s", DbType="NVarChar(200)")]
		public string tcp_s
		{
			get
			{
				return this._tcp_s;
			}
			set
			{
				if ((this._tcp_s != value))
				{
					this._tcp_s = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tcp_d", DbType="NVarChar(200)")]
		public string tcp_d
		{
			get
			{
				return this._tcp_d;
			}
			set
			{
				if ((this._tcp_d != value))
				{
					this._tcp_d = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_udp_s", DbType="NVarChar(200)")]
		public string udp_s
		{
			get
			{
				return this._udp_s;
			}
			set
			{
				if ((this._udp_s != value))
				{
					this._udp_s = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_udp_d", DbType="NVarChar(200)")]
		public string udp_d
		{
			get
			{
				return this._udp_d;
			}
			set
			{
				if ((this._udp_d != value))
				{
					this._udp_d = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lac", DbType="NVarChar(200)")]
		public string lac
		{
			get
			{
				return this._lac;
			}
			set
			{
				if ((this._lac != value))
				{
					this._lac = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ci", DbType="NVarChar(200)")]
		public string ci
		{
			get
			{
				return this._ci;
			}
			set
			{
				if ((this._ci != value))
				{
					this._ci = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_http_type", DbType="NVarChar(200)")]
		public string http_type
		{
			get
			{
				return this._http_type;
			}
			set
			{
				if ((this._http_type != value))
				{
					this._http_type = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_wsp_type", DbType="NVarChar(200)")]
		public string wsp_type
		{
			get
			{
				return this._wsp_type;
			}
			set
			{
				if ((this._wsp_type != value))
				{
					this._wsp_type = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_smtp_type", DbType="NVarChar(200)")]
		public string smtp_type
		{
			get
			{
				return this._smtp_type;
			}
			set
			{
				if ((this._smtp_type != value))
				{
					this._smtp_type = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rtsp_type", DbType="NVarChar(200)")]
		public string rtsp_type
		{
			get
			{
				return this._rtsp_type;
			}
			set
			{
				if ((this._rtsp_type != value))
				{
					this._rtsp_type = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ip_length", DbType="Int")]
		public System.Nullable<int> ip_length
		{
			get
			{
				return this._ip_length;
			}
			set
			{
				if ((this._ip_length != value))
				{
					this._ip_length = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_imei", DbType="NVarChar(200)")]
		public string imei
		{
			get
			{
				return this._imei;
			}
			set
			{
				if ((this._imei != value))
				{
					this._imei = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mmse", DbType="NVarChar(200)")]
		public string mmse
		{
			get
			{
				return this._mmse;
			}
			set
			{
				if ((this._mmse != value))
				{
					this._mmse = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bitrorrent", DbType="NVarChar(200)")]
		public string bitrorrent
		{
			get
			{
				return this._bitrorrent;
			}
			set
			{
				if ((this._bitrorrent != value))
				{
					this._bitrorrent = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_oicqVersion", DbType="NVarChar(200)")]
		public string oicqVersion
		{
			get
			{
				return this._oicqVersion;
			}
			set
			{
				if ((this._oicqVersion != value))
				{
					this._oicqVersion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_edonkey", DbType="NVarChar(200)")]
		public string edonkey
		{
			get
			{
				return this._edonkey;
			}
			set
			{
				if ((this._edonkey != value))
				{
					this._edonkey = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_imsi", DbType="NVarChar(200)")]
		public string imsi
		{
			get
			{
				return this._imsi;
			}
			set
			{
				if ((this._imsi != value))
				{
					this._imsi = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ciBVCI")]
	public partial class ciBVCI : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private decimal _ciBVCI_id;
		
		private System.Nullable<int> _fileNum;
		
		private string _lacCi;
		
		private string _bvci;
		
		private string _ciCoverType;
		
		private string _ciCoverClass;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnciBVCI_idChanging(decimal value);
    partial void OnciBVCI_idChanged();
    partial void OnfileNumChanging(System.Nullable<int> value);
    partial void OnfileNumChanged();
    partial void OnlacCiChanging(string value);
    partial void OnlacCiChanged();
    partial void OnbvciChanging(string value);
    partial void OnbvciChanged();
    partial void OnciCoverTypeChanging(string value);
    partial void OnciCoverTypeChanged();
    partial void OnciCoverClassChanging(string value);
    partial void OnciCoverClassChanged();
    #endregion
		
		public ciBVCI()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ciBVCI_id", AutoSync=AutoSync.OnInsert, DbType="Decimal(18,0) NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public decimal ciBVCI_id
		{
			get
			{
				return this._ciBVCI_id;
			}
			set
			{
				if ((this._ciBVCI_id != value))
				{
					this.OnciBVCI_idChanging(value);
					this.SendPropertyChanging();
					this._ciBVCI_id = value;
					this.SendPropertyChanged("ciBVCI_id");
					this.OnciBVCI_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fileNum", DbType="Int")]
		public System.Nullable<int> fileNum
		{
			get
			{
				return this._fileNum;
			}
			set
			{
				if ((this._fileNum != value))
				{
					this.OnfileNumChanging(value);
					this.SendPropertyChanging();
					this._fileNum = value;
					this.SendPropertyChanged("fileNum");
					this.OnfileNumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lacCi", DbType="NVarChar(50)")]
		public string lacCi
		{
			get
			{
				return this._lacCi;
			}
			set
			{
				if ((this._lacCi != value))
				{
					this.OnlacCiChanging(value);
					this.SendPropertyChanging();
					this._lacCi = value;
					this.SendPropertyChanged("lacCi");
					this.OnlacCiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bvci", DbType="NVarChar(50)")]
		public string bvci
		{
			get
			{
				return this._bvci;
			}
			set
			{
				if ((this._bvci != value))
				{
					this.OnbvciChanging(value);
					this.SendPropertyChanging();
					this._bvci = value;
					this.SendPropertyChanged("bvci");
					this.OnbvciChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ciCoverType", DbType="NVarChar(50)")]
		public string ciCoverType
		{
			get
			{
				return this._ciCoverType;
			}
			set
			{
				if ((this._ciCoverType != value))
				{
					this.OnciCoverTypeChanging(value);
					this.SendPropertyChanging();
					this._ciCoverType = value;
					this.SendPropertyChanged("ciCoverType");
					this.OnciCoverTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ciCoverClass", DbType="NVarChar(5)")]
		public string ciCoverClass
		{
			get
			{
				return this._ciCoverClass;
			}
			set
			{
				if ((this._ciCoverClass != value))
				{
					this.OnciCoverClassChanging(value);
					this.SendPropertyChanging();
					this._ciCoverClass = value;
					this.SendPropertyChanged("ciCoverClass");
					this.OnciCoverClassChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.imeiType")]
	public partial class imeiType : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private decimal _imeiType_id;
		
		private string _imei;
		
		private string _imeiFactory;
		
		private string _imeiModel;
		
		private string _imeiClass;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnimeiType_idChanging(decimal value);
    partial void OnimeiType_idChanged();
    partial void OnimeiChanging(string value);
    partial void OnimeiChanged();
    partial void OnimeiFactoryChanging(string value);
    partial void OnimeiFactoryChanged();
    partial void OnimeiModelChanging(string value);
    partial void OnimeiModelChanged();
    partial void OnimeiClassChanging(string value);
    partial void OnimeiClassChanged();
    #endregion
		
		public imeiType()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_imeiType_id", AutoSync=AutoSync.OnInsert, DbType="Decimal(18,0) NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public decimal imeiType_id
		{
			get
			{
				return this._imeiType_id;
			}
			set
			{
				if ((this._imeiType_id != value))
				{
					this.OnimeiType_idChanging(value);
					this.SendPropertyChanging();
					this._imeiType_id = value;
					this.SendPropertyChanged("imeiType_id");
					this.OnimeiType_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_imei", DbType="NVarChar(50)")]
		public string imei
		{
			get
			{
				return this._imei;
			}
			set
			{
				if ((this._imei != value))
				{
					this.OnimeiChanging(value);
					this.SendPropertyChanging();
					this._imei = value;
					this.SendPropertyChanged("imei");
					this.OnimeiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_imeiFactory", DbType="NVarChar(50)")]
		public string imeiFactory
		{
			get
			{
				return this._imeiFactory;
			}
			set
			{
				if ((this._imeiFactory != value))
				{
					this.OnimeiFactoryChanging(value);
					this.SendPropertyChanging();
					this._imeiFactory = value;
					this.SendPropertyChanged("imeiFactory");
					this.OnimeiFactoryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_imeiModel", DbType="NVarChar(500)")]
		public string imeiModel
		{
			get
			{
				return this._imeiModel;
			}
			set
			{
				if ((this._imeiModel != value))
				{
					this.OnimeiModelChanging(value);
					this.SendPropertyChanging();
					this._imeiModel = value;
					this.SendPropertyChanged("imeiModel");
					this.OnimeiModelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_imeiClass", DbType="NVarChar(50)")]
		public string imeiClass
		{
			get
			{
				return this._imeiClass;
			}
			set
			{
				if ((this._imeiClass != value))
				{
					this.OnimeiClassChanging(value);
					this.SendPropertyChanging();
					this._imeiClass = value;
					this.SendPropertyChanged("imeiClass");
					this.OnimeiClassChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.msIMEI")]
	public partial class msIMEI : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private decimal _msIMEI_id;
		
		private System.Nullable<int> _fileNum;
		
		private string _tlli;
		
		private string _imsi;
		
		private string _imei;
		
		private string _imeitype;
		
		private string _imeiclass;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmsIMEI_idChanging(decimal value);
    partial void OnmsIMEI_idChanged();
    partial void OnfileNumChanging(System.Nullable<int> value);
    partial void OnfileNumChanged();
    partial void OntlliChanging(string value);
    partial void OntlliChanged();
    partial void OnimsiChanging(string value);
    partial void OnimsiChanged();
    partial void OnimeiChanging(string value);
    partial void OnimeiChanged();
    partial void OnimeitypeChanging(string value);
    partial void OnimeitypeChanged();
    partial void OnimeiclassChanging(string value);
    partial void OnimeiclassChanged();
    #endregion
		
		public msIMEI()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_msIMEI_id", AutoSync=AutoSync.OnInsert, DbType="Decimal(18,0) NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public decimal msIMEI_id
		{
			get
			{
				return this._msIMEI_id;
			}
			set
			{
				if ((this._msIMEI_id != value))
				{
					this.OnmsIMEI_idChanging(value);
					this.SendPropertyChanging();
					this._msIMEI_id = value;
					this.SendPropertyChanged("msIMEI_id");
					this.OnmsIMEI_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fileNum", DbType="Int")]
		public System.Nullable<int> fileNum
		{
			get
			{
				return this._fileNum;
			}
			set
			{
				if ((this._fileNum != value))
				{
					this.OnfileNumChanging(value);
					this.SendPropertyChanging();
					this._fileNum = value;
					this.SendPropertyChanged("fileNum");
					this.OnfileNumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tlli", DbType="NVarChar(50)")]
		public string tlli
		{
			get
			{
				return this._tlli;
			}
			set
			{
				if ((this._tlli != value))
				{
					this.OntlliChanging(value);
					this.SendPropertyChanging();
					this._tlli = value;
					this.SendPropertyChanged("tlli");
					this.OntlliChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_imsi", DbType="NVarChar(50)")]
		public string imsi
		{
			get
			{
				return this._imsi;
			}
			set
			{
				if ((this._imsi != value))
				{
					this.OnimsiChanging(value);
					this.SendPropertyChanging();
					this._imsi = value;
					this.SendPropertyChanged("imsi");
					this.OnimsiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_imei", DbType="NVarChar(50)")]
		public string imei
		{
			get
			{
				return this._imei;
			}
			set
			{
				if ((this._imei != value))
				{
					this.OnimeiChanging(value);
					this.SendPropertyChanging();
					this._imei = value;
					this.SendPropertyChanged("imei");
					this.OnimeiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_imeitype", DbType="NVarChar(50)")]
		public string imeitype
		{
			get
			{
				return this._imeitype;
			}
			set
			{
				if ((this._imeitype != value))
				{
					this.OnimeitypeChanging(value);
					this.SendPropertyChanging();
					this._imeitype = value;
					this.SendPropertyChanged("imeitype");
					this.OnimeitypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_imeiclass", DbType="NVarChar(50)")]
		public string imeiclass
		{
			get
			{
				return this._imeiclass;
			}
			set
			{
				if ((this._imeiclass != value))
				{
					this.OnimeiclassChanging(value);
					this.SendPropertyChanging();
					this._imeiclass = value;
					this.SendPropertyChanged("imeiclass");
					this.OnimeiclassChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.mLocatingType")]
	public partial class mLocatingType : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Nullable<int> _fileNum;
		
		private System.Nullable<int> _frame;
		
		private string _bvci;
		
		private string _lacCI;
		
		private string _ciConverType;
		
		private string _ciConverClass;
		
		private string _tlli;
		
		private string _imsi;
		
		private string _imei;
		
		private string _msimeiType;
		
		private string _msimeiClass;
		
		private string _trafficType;
		
		private string _uriType;
		
		private string _protocolType;
		
		private string _portType;
		
		private string _responseType;
		
		private System.Nullable<int> _mLen;
		
		private decimal _MLocatingType_id;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnfileNumChanging(System.Nullable<int> value);
    partial void OnfileNumChanged();
    partial void OnframeChanging(System.Nullable<int> value);
    partial void OnframeChanged();
    partial void OnbvciChanging(string value);
    partial void OnbvciChanged();
    partial void OnlacCIChanging(string value);
    partial void OnlacCIChanged();
    partial void OnciConverTypeChanging(string value);
    partial void OnciConverTypeChanged();
    partial void OnciConverClassChanging(string value);
    partial void OnciConverClassChanged();
    partial void OntlliChanging(string value);
    partial void OntlliChanged();
    partial void OnimsiChanging(string value);
    partial void OnimsiChanged();
    partial void OnimeiChanging(string value);
    partial void OnimeiChanged();
    partial void OnmsimeiTypeChanging(string value);
    partial void OnmsimeiTypeChanged();
    partial void OnmsimeiClassChanging(string value);
    partial void OnmsimeiClassChanged();
    partial void OntrafficTypeChanging(string value);
    partial void OntrafficTypeChanged();
    partial void OnuriTypeChanging(string value);
    partial void OnuriTypeChanged();
    partial void OnprotocolTypeChanging(string value);
    partial void OnprotocolTypeChanged();
    partial void OnportTypeChanging(string value);
    partial void OnportTypeChanged();
    partial void OnresponseTypeChanging(string value);
    partial void OnresponseTypeChanged();
    partial void OnmLenChanging(System.Nullable<int> value);
    partial void OnmLenChanged();
    partial void OnMLocatingType_idChanging(decimal value);
    partial void OnMLocatingType_idChanged();
    #endregion
		
		public mLocatingType()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fileNum", DbType="Int")]
		public System.Nullable<int> fileNum
		{
			get
			{
				return this._fileNum;
			}
			set
			{
				if ((this._fileNum != value))
				{
					this.OnfileNumChanging(value);
					this.SendPropertyChanging();
					this._fileNum = value;
					this.SendPropertyChanged("fileNum");
					this.OnfileNumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_frame", DbType="Int")]
		public System.Nullable<int> frame
		{
			get
			{
				return this._frame;
			}
			set
			{
				if ((this._frame != value))
				{
					this.OnframeChanging(value);
					this.SendPropertyChanging();
					this._frame = value;
					this.SendPropertyChanged("frame");
					this.OnframeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bvci", DbType="NVarChar(50)")]
		public string bvci
		{
			get
			{
				return this._bvci;
			}
			set
			{
				if ((this._bvci != value))
				{
					this.OnbvciChanging(value);
					this.SendPropertyChanging();
					this._bvci = value;
					this.SendPropertyChanged("bvci");
					this.OnbvciChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lacCI", DbType="NVarChar(50)")]
		public string lacCI
		{
			get
			{
				return this._lacCI;
			}
			set
			{
				if ((this._lacCI != value))
				{
					this.OnlacCIChanging(value);
					this.SendPropertyChanging();
					this._lacCI = value;
					this.SendPropertyChanged("lacCI");
					this.OnlacCIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ciConverType", DbType="NVarChar(50)")]
		public string ciConverType
		{
			get
			{
				return this._ciConverType;
			}
			set
			{
				if ((this._ciConverType != value))
				{
					this.OnciConverTypeChanging(value);
					this.SendPropertyChanging();
					this._ciConverType = value;
					this.SendPropertyChanged("ciConverType");
					this.OnciConverTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ciConverClass", DbType="NVarChar(5)")]
		public string ciConverClass
		{
			get
			{
				return this._ciConverClass;
			}
			set
			{
				if ((this._ciConverClass != value))
				{
					this.OnciConverClassChanging(value);
					this.SendPropertyChanging();
					this._ciConverClass = value;
					this.SendPropertyChanged("ciConverClass");
					this.OnciConverClassChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tlli", DbType="NVarChar(50)")]
		public string tlli
		{
			get
			{
				return this._tlli;
			}
			set
			{
				if ((this._tlli != value))
				{
					this.OntlliChanging(value);
					this.SendPropertyChanging();
					this._tlli = value;
					this.SendPropertyChanged("tlli");
					this.OntlliChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_imsi", DbType="NVarChar(50)")]
		public string imsi
		{
			get
			{
				return this._imsi;
			}
			set
			{
				if ((this._imsi != value))
				{
					this.OnimsiChanging(value);
					this.SendPropertyChanging();
					this._imsi = value;
					this.SendPropertyChanged("imsi");
					this.OnimsiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_imei", DbType="NVarChar(50)")]
		public string imei
		{
			get
			{
				return this._imei;
			}
			set
			{
				if ((this._imei != value))
				{
					this.OnimeiChanging(value);
					this.SendPropertyChanging();
					this._imei = value;
					this.SendPropertyChanged("imei");
					this.OnimeiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_msimeiType", DbType="NVarChar(500)")]
		public string msimeiType
		{
			get
			{
				return this._msimeiType;
			}
			set
			{
				if ((this._msimeiType != value))
				{
					this.OnmsimeiTypeChanging(value);
					this.SendPropertyChanging();
					this._msimeiType = value;
					this.SendPropertyChanged("msimeiType");
					this.OnmsimeiTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_msimeiClass", DbType="NVarChar(50)")]
		public string msimeiClass
		{
			get
			{
				return this._msimeiClass;
			}
			set
			{
				if ((this._msimeiClass != value))
				{
					this.OnmsimeiClassChanging(value);
					this.SendPropertyChanging();
					this._msimeiClass = value;
					this.SendPropertyChanged("msimeiClass");
					this.OnmsimeiClassChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_trafficType", DbType="NVarChar(50)")]
		public string trafficType
		{
			get
			{
				return this._trafficType;
			}
			set
			{
				if ((this._trafficType != value))
				{
					this.OntrafficTypeChanging(value);
					this.SendPropertyChanging();
					this._trafficType = value;
					this.SendPropertyChanged("trafficType");
					this.OntrafficTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_uriType", DbType="NVarChar(500)")]
		public string uriType
		{
			get
			{
				return this._uriType;
			}
			set
			{
				if ((this._uriType != value))
				{
					this.OnuriTypeChanging(value);
					this.SendPropertyChanging();
					this._uriType = value;
					this.SendPropertyChanged("uriType");
					this.OnuriTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_protocolType", DbType="NVarChar(50)")]
		public string protocolType
		{
			get
			{
				return this._protocolType;
			}
			set
			{
				if ((this._protocolType != value))
				{
					this.OnprotocolTypeChanging(value);
					this.SendPropertyChanging();
					this._protocolType = value;
					this.SendPropertyChanged("protocolType");
					this.OnprotocolTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_portType", DbType="NVarChar(50)")]
		public string portType
		{
			get
			{
				return this._portType;
			}
			set
			{
				if ((this._portType != value))
				{
					this.OnportTypeChanging(value);
					this.SendPropertyChanging();
					this._portType = value;
					this.SendPropertyChanged("portType");
					this.OnportTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_responseType", DbType="NVarChar(50)")]
		public string responseType
		{
			get
			{
				return this._responseType;
			}
			set
			{
				if ((this._responseType != value))
				{
					this.OnresponseTypeChanging(value);
					this.SendPropertyChanging();
					this._responseType = value;
					this.SendPropertyChanged("responseType");
					this.OnresponseTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mLen", DbType="Int")]
		public System.Nullable<int> mLen
		{
			get
			{
				return this._mLen;
			}
			set
			{
				if ((this._mLen != value))
				{
					this.OnmLenChanging(value);
					this.SendPropertyChanging();
					this._mLen = value;
					this.SendPropertyChanged("mLen");
					this.OnmLenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MLocatingType_id", AutoSync=AutoSync.OnInsert, DbType="Decimal(18,0) NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public decimal MLocatingType_id
		{
			get
			{
				return this._MLocatingType_id;
			}
			set
			{
				if ((this._MLocatingType_id != value))
				{
					this.OnMLocatingType_idChanging(value);
					this.SendPropertyChanging();
					this._MLocatingType_id = value;
					this.SendPropertyChanged("MLocatingType_id");
					this.OnMLocatingType_idChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ciCoverType")]
	public partial class ciCoverType
	{
		
		private int _ciCoverType_id;
		
		private string _lacCI;
		
		private string _ciName;
		
		private string _ciCoverModel;
		
		private string _ciCoverClass;
		
		public ciCoverType()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ciCoverType_id", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int ciCoverType_id
		{
			get
			{
				return this._ciCoverType_id;
			}
			set
			{
				if ((this._ciCoverType_id != value))
				{
					this._ciCoverType_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lacCI", DbType="VarChar(65)")]
		public string lacCI
		{
			get
			{
				return this._lacCI;
			}
			set
			{
				if ((this._lacCI != value))
				{
					this._lacCI = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ciName", DbType="VarChar(32)")]
		public string ciName
		{
			get
			{
				return this._ciName;
			}
			set
			{
				if ((this._ciName != value))
				{
					this._ciName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ciCoverModel", DbType="VarChar(32)")]
		public string ciCoverModel
		{
			get
			{
				return this._ciCoverModel;
			}
			set
			{
				if ((this._ciCoverModel != value))
				{
					this._ciCoverModel = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ciCoverClass", DbType="VarChar(32)")]
		public string ciCoverClass
		{
			get
			{
				return this._ciCoverClass;
			}
			set
			{
				if ((this._ciCoverClass != value))
				{
					this._ciCoverClass = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Gb_Paging_PS")]
	public partial class Gb_Paging_PS
	{
		
		private System.Nullable<int> _FileNum;
		
		private System.Nullable<int> _PacketNum;
		
		private System.Nullable<int> _BeginFrameNum;
		
		private System.Nullable<System.DateTime> _PacketTime;
		
		private System.Nullable<int> _PacketTime_ms_;
		
		private string _DumpFor;
		
		private System.Nullable<int> _Paging_Type_PS;
		
		private string _Paging_Type_PS_time;
		
		private string _PTMSI;
		
		private string _LAC;
		
		private string _MCC;
		
		private string _MNC;
		
		private string _Gb_Link;
		
		private string _IMSI;
		
		private string _RAC;
		
		private System.Nullable<int> _PS_Paging_Repeat;
		
		private System.Nullable<int> _PS_Paging_Repeat_delayFirst;
		
		private System.Nullable<int> _Any_Uplink_PDU;
		
		private System.Nullable<int> _Any_Uplink_PDU_delayFirst;
		
		private string _CI;
		
		private string _TLLI;
		
		public Gb_Paging_PS()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FileNum", DbType="Int")]
		public System.Nullable<int> FileNum
		{
			get
			{
				return this._FileNum;
			}
			set
			{
				if ((this._FileNum != value))
				{
					this._FileNum = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PacketNum", DbType="Int")]
		public System.Nullable<int> PacketNum
		{
			get
			{
				return this._PacketNum;
			}
			set
			{
				if ((this._PacketNum != value))
				{
					this._PacketNum = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BeginFrameNum", DbType="Int")]
		public System.Nullable<int> BeginFrameNum
		{
			get
			{
				return this._BeginFrameNum;
			}
			set
			{
				if ((this._BeginFrameNum != value))
				{
					this._BeginFrameNum = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PacketTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> PacketTime
		{
			get
			{
				return this._PacketTime;
			}
			set
			{
				if ((this._PacketTime != value))
				{
					this._PacketTime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[PacketTime(ms)]", Storage="_PacketTime_ms_", DbType="Int")]
		public System.Nullable<int> PacketTime_ms_
		{
			get
			{
				return this._PacketTime_ms_;
			}
			set
			{
				if ((this._PacketTime_ms_ != value))
				{
					this._PacketTime_ms_ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DumpFor", DbType="NVarChar(30)")]
		public string DumpFor
		{
			get
			{
				return this._DumpFor;
			}
			set
			{
				if ((this._DumpFor != value))
				{
					this._DumpFor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Paging_Type_PS", DbType="Int")]
		public System.Nullable<int> Paging_Type_PS
		{
			get
			{
				return this._Paging_Type_PS;
			}
			set
			{
				if ((this._Paging_Type_PS != value))
				{
					this._Paging_Type_PS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Paging_Type_PS_time", DbType="NVarChar(200)")]
		public string Paging_Type_PS_time
		{
			get
			{
				return this._Paging_Type_PS_time;
			}
			set
			{
				if ((this._Paging_Type_PS_time != value))
				{
					this._Paging_Type_PS_time = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PTMSI", DbType="NVarChar(200)")]
		public string PTMSI
		{
			get
			{
				return this._PTMSI;
			}
			set
			{
				if ((this._PTMSI != value))
				{
					this._PTMSI = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LAC", DbType="NVarChar(200)")]
		public string LAC
		{
			get
			{
				return this._LAC;
			}
			set
			{
				if ((this._LAC != value))
				{
					this._LAC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MCC", DbType="NVarChar(200)")]
		public string MCC
		{
			get
			{
				return this._MCC;
			}
			set
			{
				if ((this._MCC != value))
				{
					this._MCC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MNC", DbType="NVarChar(200)")]
		public string MNC
		{
			get
			{
				return this._MNC;
			}
			set
			{
				if ((this._MNC != value))
				{
					this._MNC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gb_Link", DbType="NVarChar(200)")]
		public string Gb_Link
		{
			get
			{
				return this._Gb_Link;
			}
			set
			{
				if ((this._Gb_Link != value))
				{
					this._Gb_Link = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IMSI", DbType="NVarChar(200)")]
		public string IMSI
		{
			get
			{
				return this._IMSI;
			}
			set
			{
				if ((this._IMSI != value))
				{
					this._IMSI = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RAC", DbType="NVarChar(200)")]
		public string RAC
		{
			get
			{
				return this._RAC;
			}
			set
			{
				if ((this._RAC != value))
				{
					this._RAC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PS_Paging_Repeat", DbType="Int")]
		public System.Nullable<int> PS_Paging_Repeat
		{
			get
			{
				return this._PS_Paging_Repeat;
			}
			set
			{
				if ((this._PS_Paging_Repeat != value))
				{
					this._PS_Paging_Repeat = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PS_Paging_Repeat_delayFirst", DbType="Int")]
		public System.Nullable<int> PS_Paging_Repeat_delayFirst
		{
			get
			{
				return this._PS_Paging_Repeat_delayFirst;
			}
			set
			{
				if ((this._PS_Paging_Repeat_delayFirst != value))
				{
					this._PS_Paging_Repeat_delayFirst = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Any_Uplink_PDU", DbType="Int")]
		public System.Nullable<int> Any_Uplink_PDU
		{
			get
			{
				return this._Any_Uplink_PDU;
			}
			set
			{
				if ((this._Any_Uplink_PDU != value))
				{
					this._Any_Uplink_PDU = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Any_Uplink_PDU_delayFirst", DbType="Int")]
		public System.Nullable<int> Any_Uplink_PDU_delayFirst
		{
			get
			{
				return this._Any_Uplink_PDU_delayFirst;
			}
			set
			{
				if ((this._Any_Uplink_PDU_delayFirst != value))
				{
					this._Any_Uplink_PDU_delayFirst = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CI", DbType="NVarChar(200)")]
		public string CI
		{
			get
			{
				return this._CI;
			}
			set
			{
				if ((this._CI != value))
				{
					this._CI = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TLLI", DbType="NVarChar(200)")]
		public string TLLI
		{
			get
			{
				return this._TLLI;
			}
			set
			{
				if ((this._TLLI != value))
				{
					this._TLLI = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
