<?xml version="1.0" encoding="utf-8"?><Database Name="IP_stream" EntityNamespace="IP_stream.Linq" ContextNamespace="IP_stream.Linq" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="dbo.IP_stream" Member="IP_stream">
    <Type Name="IP_stream">
      <Column Name="FileNum" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PacketNum" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BeginFrameNum" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PacketTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="[PacketTime(ms)]" Member="PacketTime_ms_" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DumpFor" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="IPstream" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IPstream_PackLen" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IPstream_MsgType" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="bvci" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="tlli" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="link" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="http_uri" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="http_host" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="http_x_online" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="wsp_uri" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="ip_s" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="ip_d" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="tcp_s" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="tcp_d" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="udp_s" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="udp_d" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="lac" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="ci" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="http_type" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="wsp_type" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="smtp_type" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="rtsp_type" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="ip_length" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="imei" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="mmse" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="bittorrent" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="oicqVersion" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="edonkey" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="imsi" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ciBVCI" Member="ciBVCI">
    <Type Name="ciBVCI">
      <Column Name="ciBVCI_id" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL IDENTITY" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="fileNum" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="lacCi" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="bvci" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ciAllocPDCH" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ciUsePDCH" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.imeiType" Member="imeiType">
    <Type Name="imeiType">
      <Column Name="imeiType_id" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL IDENTITY" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="imei" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="imeiFactory" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="imeiModel" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="imeiClass" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.msIMEI" Member="msIMEI">
    <Type Name="msIMEI">
      <Column Name="msIMEI_id" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL IDENTITY" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="fileNum" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="tlli" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="imsi" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="imei" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="imeitype" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="imeiclass" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.mLocatingType" Member="mLocatingType">
    <Type Name="mLocatingType">
      <Column Name="fileNum" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="frame" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="bvci" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="lacCI" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ciCoverAllocPDCH" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ciCoverUsePDCH" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="tlli" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="imsi" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="imei" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="msimeiType" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="msimeiClass" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="trafficType" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="uriType" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="protocolType" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="portType" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="responseType" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="mLen" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MLocatingType_id" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL IDENTITY" CanBeNull="false" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.ciCoverType" Member="ciCoverType">
    <Type Name="ciCoverType">
      <Column Name="ciCoverType_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="lacCI" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="ciName" Type="System.String" DbType="VarChar(32)" CanBeNull="true" />
      <Column Name="ciAllocPDCH" Type="System.String" DbType="VarChar(32)" CanBeNull="true" />
      <Column Name="ciUsePDCH" Type="System.String" DbType="VarChar(32)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Gb_Paging_PS" Member="Gb_Paging_PS">
    <Type Name="Gb_Paging_PS">
      <Column Name="FileNum" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PacketNum" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BeginFrameNum" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PacketTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="[PacketTime(ms)]" Member="PacketTime_ms_" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DumpFor" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="Paging_Type_PS" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Paging_Type_PS_time" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="PTMSI" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="LAC" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="MCC" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="MNC" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Gb_Link" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="IMSI" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="RAC" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="PS_Paging_Repeat" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PS_Paging_Repeat_delayFirst" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Any_Uplink_PDU" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Any_Uplink_PDU_delayFirst" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CI" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="TLLI" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="" Member="OpCiPDCH">
    <Type Name="OpCiPDCH">
      <Column Name="LacCi" Type="System.String" CanBeNull="false" />
      <Column Name="CiKbps" Type="System.Double" CanBeNull="false" />
      <Column Name="CiPDCH" Type="System.Double" CanBeNull="false" />
      <Column Name="X0_Coefficient" Type="System.Double" CanBeNull="false" />
      <Column Name="StreamingMedia" Type="System.Double" CanBeNull="false" />
      <Column Name="StockCategory" Type="System.Double" CanBeNull="false" />
      <Column Name="OtherCategory" Type="System.Double" CanBeNull="false" />
      <Column Name="MMS" Type="System.Double" CanBeNull="false" />
      <Column Name="IM" Type="System.Double" CanBeNull="false" />
      <Column Name="GeneralDownloads" Type="System.Double" CanBeNull="false" />
      <Column Name="GameCategory" Type="System.Double" CanBeNull="false" />
      <Column Name="BrowseCategory" Type="System.Double" CanBeNull="false" />
      <Column Name="P2P" Type="System.Double" CanBeNull="false" />
      <Column Name="OpCiPDCH_id" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL IDENTITY" CanBeNull="false" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="" Member="OpPaingTime">
    <Type Name="OpPaingTime">
      <Column Name="LacCi" Type="System.String" CanBeNull="false" />
      <Column Name="mMessage" Type="System.Double" CanBeNull="false" />
      <Column Name="mResponeSucc" Type="System.Double" CanBeNull="false" />
      <Column Name="mDelay" Type="System.Double" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="" Member="OpPdchModel">
    <Type Name="OpPdchModel">
      <Column Name="小区号Ci" Type="System.String" CanBeNull="false" />
      <Column Name="小区总速率" Type="System.Double" CanBeNull="false" />
      <Column Name="模型计算需求数ComputePDCH" Type="System.Double" CanBeNull="false" />
      <Column Name="模型计算增加或减少数NeedPDCH" Type="System.Double" CanBeNull="false" />
      <Column Name="统计值_使用PDCH" Type="System.Double" CanBeNull="false" />
      <Column Name="偏移量Offset" Type="System.Double" CanBeNull="false" />
      <Column Name="业务速率IM" Type="System.Double" CanBeNull="false" />
      <Column Name="业务速率GeneralDownloads_StreamingMedia_P2P_GameCategory"  Type="System.Double" CanBeNull="false" />
      <Column Name="业务速率BrowseCategory_StockCategory"  Type="System.Double" CanBeNull="false" />
      <Column Name="业务速率MMS"  Type="System.Double"  CanBeNull="false" />
      <Column Name="业务速率OtherCategory"  Type="System.Double" CanBeNull="false" />
      <Column Name="PS寻呼次数" Type="System.Double" CanBeNull="false" />
      <Column Name="PS寻呼成功率" Type="System.Double" CanBeNull="false" />
      <Column Name="PS寻呼时延" Type="System.Double" CanBeNull="false" />
    </Type>
  </Table>
</Database>