<?xml version="1.0" encoding="utf-8"?><Database Name="IP_Stream" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.\sqlexpress;Initial Catalog=IP_Stream;Integrated Security=True" SettingsObjectName="IP_stream.Properties.Settings" SettingsPropertyName="IP_StreamConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.IP_stream" Member="IP_stream">
    <Type Name="IP_stream">
      <Column Name="FileNum" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PacketNum" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BeginFrameNum" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PacketTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="[PacketTime(ms)]" Member="PacketTime_ms_" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DumpFor" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="IPstream" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IPstream_PackLen" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IPstream_MsgType" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="bvci" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="tlli" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="link" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="http_uri" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="http_host" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="http_x_online" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="wsp_uri" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="ip_s" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="ip_d" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="tcp_s" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="tcp_d" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="udp_s" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="udp_d" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="lac" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="ci" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="http_type" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="wsp_type" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="smtp_type" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="rtsp_type" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="ip_length" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="imei" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="mmse" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="bitrorrent" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="oicqVersion" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="edonkey" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="imsi" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ciBVCI" Member="ciBVCI">
    <Type Name="ciBVCI">
      <Column Name="ciBVCI_id" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="fileNum" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="lacCi" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="bvci" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ciCoverType" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ciCoverClass" Type="System.String" DbType="NVarChar(5)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.imeiType" Member="imeiType">
    <Type Name="imeiType">
      <Column Name="imeiType_id" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="imei" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="imeiFactory" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="imeiModel" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="imeiClass" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.msIMEI" Member="msIMEI">
    <Type Name="msIMEI">
      <Column Name="msIMEI_id" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="fileNum" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="tlli" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="imsi" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="imei" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="imeitype" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="imeiclass" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.mLocatingType" Member="mLocatingType">
    <Type Name="mLocatingType">
      <Column Name="fileNum" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="frame" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="bvci" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="lacCI" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ciConverType" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ciConverClass" Type="System.String" DbType="NVarChar(5)" CanBeNull="true" />
      <Column Name="tlli" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="imsi" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="imei" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="msimeiType" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="msimeiClass" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="trafficType" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="uriType" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="protocolType" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="portType" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="responseType" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="mLen" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MLocatingType_id" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.ciCoverType" Member="ciCoverType">
    <Type Name="ciCoverType">
      <Column Name="ciCoverType_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="lacCI" Type="System.String" DbType="VarChar(65)" CanBeNull="true" />
      <Column Name="ciName" Type="System.String" DbType="VarChar(32)" CanBeNull="true" />
      <Column Name="ciCoverModel" Type="System.String" DbType="VarChar(32)" CanBeNull="true" />
      <Column Name="ciCoverClass" Type="System.String" DbType="VarChar(32)" CanBeNull="true" />
    </Type>
  </Table>
</Database>